### ISSUE TITLE
Write new endpoint action generators and middleware

### ISSUE THREAD

**Issue by DanielleHuisman** [VerenigingCampusKabel/redux-cached-api#3]
Write new action generator which generates action that use `humps` and Fetch API.
- [x] Fetch API request
- [x] Endpoint action generator
- [x] Redux middleware (see comment below)
- [x] Support async bailout function
- [x] Support async payload parse functions (e.g. the default `getJSON` from `src/util.js`)
- [x] Support both entity and custom endpoints
- [x] Support (de)camelize options (using `humps`)
- [x] Support normalizr

**Comment by DanielleHuisman** [comment]
With the rewrite one of the plans was to use `redux-thunk`, however there are multiple reasons to keep it as middleware (the state of v1.x):
- Performance: only one function handles all complicated API requests instead of generating the same function over and over again (e.g. with Redux Thunk or Saga).
- Action history: with Redux Thunk it's difficult/impossible to fully serialize actions and see where certain data comes into play. Middleware helps with this as all data is contained in actions.
- Redux Thunk / Saga is being considered as quite an anti-pattern for multiple reasons (including the one(s) above). A quick search on Google will help you find a better explanation of this topic.

**TODO:** Re-implement middleware and remove `redux-thunk`. 

P.S. consider using the request action type as middleware "trigger" as this action type is basically pointless and prevents a duplicate application re-renders.
